/*
Dispatch Api 3.0

Testing MissionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_MissionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MissionsAPIService CancelMission", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.MissionsAPI.CancelMission(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MissionsAPIService CreateMission", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MissionsAPI.CreateMission(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MissionsAPIService GetMissionById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.MissionsAPI.GetMissionById(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MissionsAPIService GetMissionByMissionNumber", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MissionsAPI.GetMissionByMissionNumber(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MissionsAPIService MissionCreationDryRun", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MissionsAPI.MissionCreationDryRun(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MissionsAPIService MissionUpdateDryRun", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.MissionsAPI.MissionUpdateDryRun(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MissionsAPIService UpdateMission", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.MissionsAPI.UpdateMission(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
