/*
Dispatch Api 3.0

Testing TransportDocumentLinksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_TransportDocumentLinksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TransportDocumentLinksAPIService CreateTransportDocumentLink", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportDocumentLinksAPI.CreateTransportDocumentLink(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportDocumentLinksAPIService DeleteTransportDocumentLink", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var linkId string

		httpRes, err := apiClient.TransportDocumentLinksAPI.DeleteTransportDocumentLink(context.Background(), uid, linkId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportDocumentLinksAPIService GetTransportDocumentLinkById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var linkId string

		resp, httpRes, err := apiClient.TransportDocumentLinksAPI.GetTransportDocumentLinkById(context.Background(), uid, linkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportDocumentLinksAPIService GetTransportDocumentLinks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportDocumentLinksAPI.GetTransportDocumentLinks(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
