/*
Dispatch Api 3.0

Testing CustomersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_CustomersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CustomersAPIService CheckCustomerDeletionConstraints", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.CustomersAPI.CheckCustomerDeletionConstraints(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomersAPIService CreateCustomer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CustomersAPI.CreateCustomer(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomersAPIService DeleteCustomer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.CustomersAPI.DeleteCustomer(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomersAPIService GetCustomParameterValues", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var parameterId int32

		resp, httpRes, err := apiClient.CustomersAPI.GetCustomParameterValues(context.Background(), uid, parameterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomersAPIService GetCustomParameters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.CustomersAPI.GetCustomParameters(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomersAPIService GetCustomerByCode", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CustomersAPI.GetCustomerByCode(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomersAPIService GetCustomerById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.CustomersAPI.GetCustomerById(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomersAPIService GetCustomerReferences", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.CustomersAPI.GetCustomerReferences(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomersAPIService GetCustomers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CustomersAPI.GetCustomers(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomersAPIService UpdateCustomer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.CustomersAPI.UpdateCustomer(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
