/*
Dispatch Api 3.0

Testing PricingPathsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_PricingPathsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PricingPathsAPIService GetPricingPathAdditionalUnits", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pricingPathId int32

		resp, httpRes, err := apiClient.PricingPathsAPI.GetPricingPathAdditionalUnits(context.Background(), pricingPathId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PricingPathsAPIService GetPricingPathById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pricingPathId int32

		resp, httpRes, err := apiClient.PricingPathsAPI.GetPricingPathById(context.Background(), pricingPathId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PricingPathsAPIService GetPricingPathSubServiceUnitPricingSlots", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pricingPathId int32

		resp, httpRes, err := apiClient.PricingPathsAPI.GetPricingPathSubServiceUnitPricingSlots(context.Background(), pricingPathId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PricingPathsAPIService GetPricingPathSubServices", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pricingPathId int32

		resp, httpRes, err := apiClient.PricingPathsAPI.GetPricingPathSubServices(context.Background(), pricingPathId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PricingPathsAPIService GetPricingPathUnitPricingSlotEquivalences", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pricingPathId int32

		resp, httpRes, err := apiClient.PricingPathsAPI.GetPricingPathUnitPricingSlotEquivalences(context.Background(), pricingPathId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PricingPathsAPIService GetPricingPaths", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PricingPathsAPI.GetPricingPaths(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
