/*
Dispatch Api 3.0

Testing TransportDocumentFilesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_TransportDocumentFilesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TransportDocumentFilesAPIService DeleteTransportDocumentFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var fileId string

		httpRes, err := apiClient.TransportDocumentFilesAPI.DeleteTransportDocumentFile(context.Background(), uid, fileId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportDocumentFilesAPIService DownloadTransportDocumentFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var fileId string

		resp, httpRes, err := apiClient.TransportDocumentFilesAPI.DownloadTransportDocumentFile(context.Background(), uid, fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportDocumentFilesAPIService GetTransportDocumentFileById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var fileId string

		resp, httpRes, err := apiClient.TransportDocumentFilesAPI.GetTransportDocumentFileById(context.Background(), uid, fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportDocumentFilesAPIService GetTransportDocumentFiles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportDocumentFilesAPI.GetTransportDocumentFiles(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportDocumentFilesAPIService UploadTransportDocumentFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportDocumentFilesAPI.UploadTransportDocumentFile(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
