/*
Dispatch Api 3.0

Testing CitiesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_CitiesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CitiesAPIService CheckCityDeletionConstraints", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cityId int32

		resp, httpRes, err := apiClient.CitiesAPI.CheckCityDeletionConstraints(context.Background(), cityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CitiesAPIService CreateCity", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CitiesAPI.CreateCity(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CitiesAPIService DeleteCity", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cityId int32

		httpRes, err := apiClient.CitiesAPI.DeleteCity(context.Background(), cityId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CitiesAPIService GetBestMatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CitiesAPI.GetBestMatch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CitiesAPIService GetCities", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CitiesAPI.GetCities(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CitiesAPIService GetCityById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cityId int32

		resp, httpRes, err := apiClient.CitiesAPI.GetCityById(context.Background(), cityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CitiesAPIService GetCityByIdAlternativeRoute", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CitiesAPI.GetCityByIdAlternativeRoute(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CitiesAPIService UpdateCity", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cityId int32

		httpRes, err := apiClient.CitiesAPI.UpdateCity(context.Background(), cityId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
