/*
Dispatch Api 3.0

Testing PackageNaturesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_PackageNaturesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PackageNaturesAPIService GetPackageNatureById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var packageNatureId int32

		resp, httpRes, err := apiClient.PackageNaturesAPI.GetPackageNatureById(context.Background(), packageNatureId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PackageNaturesAPIService GetPackageNatureReferenceValues", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var packageNatureId int32
		var referenceIndex int32

		resp, httpRes, err := apiClient.PackageNaturesAPI.GetPackageNatureReferenceValues(context.Background(), packageNatureId, referenceIndex).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PackageNaturesAPIService GetPackageNatureReferences", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var packageNatureId int32

		resp, httpRes, err := apiClient.PackageNaturesAPI.GetPackageNatureReferences(context.Background(), packageNatureId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PackageNaturesAPIService GetPackageNatures", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PackageNaturesAPI.GetPackageNatures(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
