/*
Dispatch Api 3.0

Testing EdiEquivalenceConfigurationsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_EdiEquivalenceConfigurationsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EdiEquivalenceConfigurationsAPIService GetCustomerEquivalencesConfigurationByUid", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.EdiEquivalenceConfigurationsAPI.GetCustomerEquivalencesConfigurationByUid(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdiEquivalenceConfigurationsAPIService GetCustomerEquivalencesConfigurations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EdiEquivalenceConfigurationsAPI.GetCustomerEquivalencesConfigurations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdiEquivalenceConfigurationsAPIService GetPackageNatureEquivalencesConfigurationByUid", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.EdiEquivalenceConfigurationsAPI.GetPackageNatureEquivalencesConfigurationByUid(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdiEquivalenceConfigurationsAPIService GetPackageNatureEquivalencesConfigurations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EdiEquivalenceConfigurationsAPI.GetPackageNatureEquivalencesConfigurations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdiEquivalenceConfigurationsAPIService GetServiceEquivalencesConfigurationByUid", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.EdiEquivalenceConfigurationsAPI.GetServiceEquivalencesConfigurationByUid(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdiEquivalenceConfigurationsAPIService GetServiceEquivalencesConfigurations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EdiEquivalenceConfigurationsAPI.GetServiceEquivalencesConfigurations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdiEquivalenceConfigurationsAPIService GetSubstateEquivalencesConfigurationByUid", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.EdiEquivalenceConfigurationsAPI.GetSubstateEquivalencesConfigurationByUid(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdiEquivalenceConfigurationsAPIService GetSubstateEquivalencesConfigurations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EdiEquivalenceConfigurationsAPI.GetSubstateEquivalencesConfigurations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
