/*
Dispatch Api 3.0

Testing TransportsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_TransportsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TransportsAPIService ApplyHistoryStateOnTransportPackageLine", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var packageLineId int32

		httpRes, err := apiClient.TransportsAPI.ApplyHistoryStateOnTransportPackageLine(context.Background(), uid, packageLineId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService ApplySubState", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.TransportsAPI.ApplySubState(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService ApplyTransportCancelledStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.TransportsAPI.ApplyTransportCancelledStatus(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService ApplyTransportDeliveredStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.TransportsAPI.ApplyTransportDeliveredStatus(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService ApplyTransportPickedUpStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.TransportsAPI.ApplyTransportPickedUpStatus(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService ApplyTransportTerminatedStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.TransportsAPI.ApplyTransportTerminatedStatus(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService CheckSeveralTransportsAssignmentConstraints", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TransportsAPI.CheckSeveralTransportsAssignmentConstraints(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService CheckTransportAssignmentsConstraints", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.CheckTransportAssignmentsConstraints(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService DefragmentTransport", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.TransportsAPI.DefragmentTransport(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService FragmentTransport", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.TransportsAPI.FragmentTransport(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportAirData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportAirData(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportBillAddress", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportBillAddress(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportByTransportIdentifier", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportByTransportIdentifier(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportByUniqueIdentifier", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportByUniqueIdentifier(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportCommunicationConfiguration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportCommunicationConfiguration(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportCustomerCustomParameters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportCustomerCustomParameters(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportDangerousGoods", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportDangerousGoods(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportHistoryLines", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportHistoryLines(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportPackageLines", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportPackageLines(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportPricing", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportPricing(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportRoute", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportRoute(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportServiceCustomParameters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportServiceCustomParameters(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportSubServices", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportSubServices(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransportTotalBulkSizes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.GetTransportTotalBulkSizes(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService GetTransports", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TransportsAPI.GetTransports(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService TransportUpdateDryRun", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		resp, httpRes, err := apiClient.TransportsAPI.TransportUpdateDryRun(context.Background(), uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService UpdateSeveralTransportsAssignment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TransportsAPI.UpdateSeveralTransportsAssignment(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService UpdateTransport", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.TransportsAPI.UpdateTransport(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService UpdateTransportAssignment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.TransportsAPI.UpdateTransportAssignment(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransportsAPIService UpdateTransportAssignmentStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string

		httpRes, err := apiClient.TransportsAPI.UpdateTransportAssignmentStatus(context.Background(), uid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
